config/routes.rb
Tworobots::Application.routes.draw do
  resources :albums

  get "home/index"

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br />
    <%= f.text_field :album %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.artist %></td>
    <td><%= album.album %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Artist:</b>
  <%= @album.artist %>
</p>

<p>
  <b>Album:</b>
  <%= @album.album %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/home/index.html.erb
<header id="main-header-wrap">
	<div id="main-header">
		<div id="main-header-content">
			<div id="logo-wrap">
				<h1 id="robot-heads">
					<a href="#">
						[oo][oo]
					</a>
				</h1>
				<nav id="main-nav">
					<ul>
						<li>
							<a href="#">
								About
							</a>
						</li>
						<li>
							<a href="#">
								Contact
							</a>
						</li>
					</ul>
				</nav>
				<h1 id="robot-text">
					<a href="#">
						Two Robots
					</a>
				</h1>
			</div>
		</div>
	</div>
</header>
<section id="main-content">
	<div id="about">
		<div id="hero-wrap">
			<div id="homepage-hero">
				[oo][oo]
			</div>
		</div>
	</div>
	<div id="legend">
		<h2>Legend</h2>
		<ul id="legend-keys">
			<li>[00]</li>
			<li>[01]</li>
			<li>[10]</li>
			<li class="last-in-row">[11]</li>
			<li>[00]</li>
			<li>[01]</li>
			<li>[10]</li>
			<li class="last-in-row">[11]</li>
			<li>[00]</li>
			<li>[01]</li>
			<li>[10]</li>
			<li class="last-in-row">[11]</li>
			<li>[00]</li>
			<li>[01]</li>
			<li>[10]</li>
			<li class="last-in-row">[11]</li>
			<li>[00]</li>
			<li>[01]</li>
			<li>[10]</li>
			<li class="last-in-row">[11]</li>
		</ul>
	</div>
	<div class="reviews">
		<h2>Music</h2>
		<ul class="artists">
			<li>Radiohead</li>
				<ul>
					<li>[01]Pablo Honey</li>
					<li>[10]The Bends</li>
					<li>[11]OK Computer</li>
						<ul>
							<li>[01]Airbag</li>
							<li>[11]Paranoid Android</li>
							<li>[10]Subterranean Homesick Alien</li>
							<li>[11]Exit Music (For A Film)</li>
							<li>[11]Let Down</li>
							<li>[10]Karma Police</li>
							<li>[10]Fitter Happier</li>
							<li>[10]Electioneering</li>
							<li>[10]Climbing Up The Walls</li>
							<li>[11]No Surprises</li>
							<li>[10]Lucky</li>
							<li>[10]The Tourist</li>
						</ul>
					<li>[10]Kid A</li>
					<li>[10]Amnesiac</li>
					<li>[10]Hail To The Thief</li>
					<li>[10]In Rainbows</li>
				</ul>
			<li>The Strokes</li>
				<ul>
					<li>Is This It?</li>
					<li>Room On Fire</li>
					<li>First Impressions Of Earth</li>
				</ul>
		</ul>
	</div>
</section>
<footer>
	
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>two robots - [oo][oo]</title>
	<link href="http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Josefin+Sans+Std+Light" rel="stylesheet"" type="text/css"">
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>